# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julinka/C++Tests/editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julinka/C++Tests/editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles /home/julinka/C++Tests/editor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncurses

# Build rule for target.
ncurses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ncurses
.PHONY : ncurses

# fast build rule for target.
ncurses/fast:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/build
.PHONY : ncurses/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.s
.PHONY : main.cpp.s

src/Bool.o: src/Bool.cpp.o

.PHONY : src/Bool.o

# target to build an object file
src/Bool.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Bool.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Bool.cpp.o
.PHONY : src/Bool.cpp.o

src/Bool.i: src/Bool.cpp.i

.PHONY : src/Bool.i

# target to preprocess a source file
src/Bool.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Bool.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Bool.cpp.i
.PHONY : src/Bool.cpp.i

src/Bool.s: src/Bool.cpp.s

.PHONY : src/Bool.s

# target to generate assembly for a file
src/Bool.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Bool.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Bool.cpp.s
.PHONY : src/Bool.cpp.s

src/Cell.o: src/Cell.cpp.o

.PHONY : src/Cell.o

# target to build an object file
src/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Cell.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Cell.cpp.o
.PHONY : src/Cell.cpp.o

src/Cell.i: src/Cell.cpp.i

.PHONY : src/Cell.i

# target to preprocess a source file
src/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Cell.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Cell.cpp.i
.PHONY : src/Cell.cpp.i

src/Cell.s: src/Cell.cpp.s

.PHONY : src/Cell.s

# target to generate assembly for a file
src/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Cell.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Cell.cpp.s
.PHONY : src/Cell.cpp.s

src/Command.o: src/Command.cpp.o

.PHONY : src/Command.o

# target to build an object file
src/Command.cpp.o:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Command.cpp.o
.PHONY : src/Command.cpp.o

src/Command.i: src/Command.cpp.i

.PHONY : src/Command.i

# target to preprocess a source file
src/Command.cpp.i:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Command.cpp.i
.PHONY : src/Command.cpp.i

src/Command.s: src/Command.cpp.s

.PHONY : src/Command.s

# target to generate assembly for a file
src/Command.cpp.s:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Command.cpp.s
.PHONY : src/Command.cpp.s

src/Expression.o: src/Expression.cpp.o

.PHONY : src/Expression.o

# target to build an object file
src/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Expression.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Expression.cpp.o
.PHONY : src/Expression.cpp.o

src/Expression.i: src/Expression.cpp.i

.PHONY : src/Expression.i

# target to preprocess a source file
src/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Expression.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Expression.cpp.i
.PHONY : src/Expression.cpp.i

src/Expression.s: src/Expression.cpp.s

.PHONY : src/Expression.s

# target to generate assembly for a file
src/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Expression.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Expression.cpp.s
.PHONY : src/Expression.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Model.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Model.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Model.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Number.o: src/Number.cpp.o

.PHONY : src/Number.o

# target to build an object file
src/Number.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Number.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Number.cpp.o
.PHONY : src/Number.cpp.o

src/Number.i: src/Number.cpp.i

.PHONY : src/Number.i

# target to preprocess a source file
src/Number.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Number.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Number.cpp.i
.PHONY : src/Number.cpp.i

src/Number.s: src/Number.cpp.s

.PHONY : src/Number.s

# target to generate assembly for a file
src/Number.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Number.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Number.cpp.s
.PHONY : src/Number.cpp.s

src/Operator.o: src/Operator.cpp.o

.PHONY : src/Operator.o

# target to build an object file
src/Operator.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Operator.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Operator.cpp.o
.PHONY : src/Operator.cpp.o

src/Operator.i: src/Operator.cpp.i

.PHONY : src/Operator.i

# target to preprocess a source file
src/Operator.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Operator.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Operator.cpp.i
.PHONY : src/Operator.cpp.i

src/Operator.s: src/Operator.cpp.s

.PHONY : src/Operator.s

# target to generate assembly for a file
src/Operator.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Operator.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Operator.cpp.s
.PHONY : src/Operator.cpp.s

src/Reference.o: src/Reference.cpp.o

.PHONY : src/Reference.o

# target to build an object file
src/Reference.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Reference.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Reference.cpp.o
.PHONY : src/Reference.cpp.o

src/Reference.i: src/Reference.cpp.i

.PHONY : src/Reference.i

# target to preprocess a source file
src/Reference.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Reference.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Reference.cpp.i
.PHONY : src/Reference.cpp.i

src/Reference.s: src/Reference.cpp.s

.PHONY : src/Reference.s

# target to generate assembly for a file
src/Reference.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Reference.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Reference.cpp.s
.PHONY : src/Reference.cpp.s

src/Text.o: src/Text.cpp.o

.PHONY : src/Text.o

# target to build an object file
src/Text.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Text.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Text.cpp.o
.PHONY : src/Text.cpp.o

src/Text.i: src/Text.cpp.i

.PHONY : src/Text.i

# target to preprocess a source file
src/Text.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Text.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Text.cpp.i
.PHONY : src/Text.cpp.i

src/Text.s: src/Text.cpp.s

.PHONY : src/Text.s

# target to generate assembly for a file
src/Text.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/Text.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/Text.cpp.s
.PHONY : src/Text.cpp.s

src/View.o: src/View.cpp.o

.PHONY : src/View.o

# target to build an object file
src/View.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/View.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/View.cpp.o
.PHONY : src/View.cpp.o

src/View.i: src/View.cpp.i

.PHONY : src/View.i

# target to preprocess a source file
src/View.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/View.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/View.cpp.i
.PHONY : src/View.cpp.i

src/View.s: src/View.cpp.s

.PHONY : src/View.s

# target to generate assembly for a file
src/View.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/src/View.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/View.cpp.s
.PHONY : src/View.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ncurses"
	@echo "... editor"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Bool.o"
	@echo "... src/Bool.i"
	@echo "... src/Bool.s"
	@echo "... src/Cell.o"
	@echo "... src/Cell.i"
	@echo "... src/Cell.s"
	@echo "... src/Command.o"
	@echo "... src/Command.i"
	@echo "... src/Command.s"
	@echo "... src/Expression.o"
	@echo "... src/Expression.i"
	@echo "... src/Expression.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Number.o"
	@echo "... src/Number.i"
	@echo "... src/Number.s"
	@echo "... src/Operator.o"
	@echo "... src/Operator.i"
	@echo "... src/Operator.s"
	@echo "... src/Reference.o"
	@echo "... src/Reference.i"
	@echo "... src/Reference.s"
	@echo "... src/Text.o"
	@echo "... src/Text.i"
	@echo "... src/Text.s"
	@echo "... src/View.o"
	@echo "... src/View.i"
	@echo "... src/View.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

