# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julinka/C++Tests/editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julinka/C++Tests/editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles /home/julinka/C++Tests/editor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncurses

# Build rule for target.
ncurses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ncurses
.PHONY : ncurses

# fast build rule for target.
ncurses/fast:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/build
.PHONY : ncurses/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

Controller/Command.o: Controller/Command.cpp.o

.PHONY : Controller/Command.o

# target to build an object file
Controller/Command.cpp.o:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Controller/Command.cpp.o
.PHONY : Controller/Command.cpp.o

Controller/Command.i: Controller/Command.cpp.i

.PHONY : Controller/Command.i

# target to preprocess a source file
Controller/Command.cpp.i:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Controller/Command.cpp.i
.PHONY : Controller/Command.cpp.i

Controller/Command.s: Controller/Command.cpp.s

.PHONY : Controller/Command.s

# target to generate assembly for a file
Controller/Command.cpp.s:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Controller/Command.cpp.s
.PHONY : Controller/Command.cpp.s

Model/Bool.o: Model/Bool.cpp.o

.PHONY : Model/Bool.o

# target to build an object file
Model/Bool.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Bool.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Bool.cpp.o
.PHONY : Model/Bool.cpp.o

Model/Bool.i: Model/Bool.cpp.i

.PHONY : Model/Bool.i

# target to preprocess a source file
Model/Bool.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Bool.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Bool.cpp.i
.PHONY : Model/Bool.cpp.i

Model/Bool.s: Model/Bool.cpp.s

.PHONY : Model/Bool.s

# target to generate assembly for a file
Model/Bool.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Bool.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Bool.cpp.s
.PHONY : Model/Bool.cpp.s

Model/Cell.o: Model/Cell.cpp.o

.PHONY : Model/Cell.o

# target to build an object file
Model/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Cell.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Cell.cpp.o
.PHONY : Model/Cell.cpp.o

Model/Cell.i: Model/Cell.cpp.i

.PHONY : Model/Cell.i

# target to preprocess a source file
Model/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Cell.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Cell.cpp.i
.PHONY : Model/Cell.cpp.i

Model/Cell.s: Model/Cell.cpp.s

.PHONY : Model/Cell.s

# target to generate assembly for a file
Model/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Cell.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Cell.cpp.s
.PHONY : Model/Cell.cpp.s

Model/Expression.o: Model/Expression.cpp.o

.PHONY : Model/Expression.o

# target to build an object file
Model/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Expression.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Expression.cpp.o
.PHONY : Model/Expression.cpp.o

Model/Expression.i: Model/Expression.cpp.i

.PHONY : Model/Expression.i

# target to preprocess a source file
Model/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Expression.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Expression.cpp.i
.PHONY : Model/Expression.cpp.i

Model/Expression.s: Model/Expression.cpp.s

.PHONY : Model/Expression.s

# target to generate assembly for a file
Model/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Expression.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Expression.cpp.s
.PHONY : Model/Expression.cpp.s

Model/Model.o: Model/Model.cpp.o

.PHONY : Model/Model.o

# target to build an object file
Model/Model.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Model.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Model.cpp.o
.PHONY : Model/Model.cpp.o

Model/Model.i: Model/Model.cpp.i

.PHONY : Model/Model.i

# target to preprocess a source file
Model/Model.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Model.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Model.cpp.i
.PHONY : Model/Model.cpp.i

Model/Model.s: Model/Model.cpp.s

.PHONY : Model/Model.s

# target to generate assembly for a file
Model/Model.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Model.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Model.cpp.s
.PHONY : Model/Model.cpp.s

Model/Number.o: Model/Number.cpp.o

.PHONY : Model/Number.o

# target to build an object file
Model/Number.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Number.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Number.cpp.o
.PHONY : Model/Number.cpp.o

Model/Number.i: Model/Number.cpp.i

.PHONY : Model/Number.i

# target to preprocess a source file
Model/Number.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Number.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Number.cpp.i
.PHONY : Model/Number.cpp.i

Model/Number.s: Model/Number.cpp.s

.PHONY : Model/Number.s

# target to generate assembly for a file
Model/Number.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Number.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Number.cpp.s
.PHONY : Model/Number.cpp.s

Model/Operator.o: Model/Operator.cpp.o

.PHONY : Model/Operator.o

# target to build an object file
Model/Operator.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Operator.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Operator.cpp.o
.PHONY : Model/Operator.cpp.o

Model/Operator.i: Model/Operator.cpp.i

.PHONY : Model/Operator.i

# target to preprocess a source file
Model/Operator.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Operator.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Operator.cpp.i
.PHONY : Model/Operator.cpp.i

Model/Operator.s: Model/Operator.cpp.s

.PHONY : Model/Operator.s

# target to generate assembly for a file
Model/Operator.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Operator.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Operator.cpp.s
.PHONY : Model/Operator.cpp.s

Model/Reference.o: Model/Reference.cpp.o

.PHONY : Model/Reference.o

# target to build an object file
Model/Reference.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Reference.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Reference.cpp.o
.PHONY : Model/Reference.cpp.o

Model/Reference.i: Model/Reference.cpp.i

.PHONY : Model/Reference.i

# target to preprocess a source file
Model/Reference.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Reference.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Reference.cpp.i
.PHONY : Model/Reference.cpp.i

Model/Reference.s: Model/Reference.cpp.s

.PHONY : Model/Reference.s

# target to generate assembly for a file
Model/Reference.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Reference.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Reference.cpp.s
.PHONY : Model/Reference.cpp.s

Model/Text.o: Model/Text.cpp.o

.PHONY : Model/Text.o

# target to build an object file
Model/Text.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Text.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Text.cpp.o
.PHONY : Model/Text.cpp.o

Model/Text.i: Model/Text.cpp.i

.PHONY : Model/Text.i

# target to preprocess a source file
Model/Text.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Text.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Text.cpp.i
.PHONY : Model/Text.cpp.i

Model/Text.s: Model/Text.cpp.s

.PHONY : Model/Text.s

# target to generate assembly for a file
Model/Text.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model/Text.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model/Text.cpp.s
.PHONY : Model/Text.cpp.s

View/View.o: View/View.cpp.o

.PHONY : View/View.o

# target to build an object file
View/View.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View/View.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View/View.cpp.o
.PHONY : View/View.cpp.o

View/View.i: View/View.cpp.i

.PHONY : View/View.i

# target to preprocess a source file
View/View.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View/View.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View/View.cpp.i
.PHONY : View/View.cpp.i

View/View.s: View/View.cpp.s

.PHONY : View/View.s

# target to generate assembly for a file
View/View.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View/View.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View/View.cpp.s
.PHONY : View/View.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ncurses"
	@echo "... editor"
	@echo "... Controller/Command.o"
	@echo "... Controller/Command.i"
	@echo "... Controller/Command.s"
	@echo "... Model/Bool.o"
	@echo "... Model/Bool.i"
	@echo "... Model/Bool.s"
	@echo "... Model/Cell.o"
	@echo "... Model/Cell.i"
	@echo "... Model/Cell.s"
	@echo "... Model/Expression.o"
	@echo "... Model/Expression.i"
	@echo "... Model/Expression.s"
	@echo "... Model/Model.o"
	@echo "... Model/Model.i"
	@echo "... Model/Model.s"
	@echo "... Model/Number.o"
	@echo "... Model/Number.i"
	@echo "... Model/Number.s"
	@echo "... Model/Operator.o"
	@echo "... Model/Operator.i"
	@echo "... Model/Operator.s"
	@echo "... Model/Reference.o"
	@echo "... Model/Reference.i"
	@echo "... Model/Reference.s"
	@echo "... Model/Text.o"
	@echo "... Model/Text.i"
	@echo "... Model/Text.s"
	@echo "... View/View.o"
	@echo "... View/View.i"
	@echo "... View/View.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

