# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julinka/C++Tests/editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julinka/C++Tests/editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/julinka/CLion/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles /home/julinka/C++Tests/editor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julinka/C++Tests/editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncurses

# Build rule for target.
ncurses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ncurses
.PHONY : ncurses

# fast build rule for target.
ncurses/fast:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/build
.PHONY : ncurses/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

Bool.o: Bool.cpp.o

.PHONY : Bool.o

# target to build an object file
Bool.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Bool.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Bool.cpp.o
.PHONY : Bool.cpp.o

Bool.i: Bool.cpp.i

.PHONY : Bool.i

# target to preprocess a source file
Bool.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Bool.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Bool.cpp.i
.PHONY : Bool.cpp.i

Bool.s: Bool.cpp.s

.PHONY : Bool.s

# target to generate assembly for a file
Bool.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Bool.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Bool.cpp.s
.PHONY : Bool.cpp.s

Cell.o: Cell.cpp.o

.PHONY : Cell.o

# target to build an object file
Cell.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Cell.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Cell.cpp.o
.PHONY : Cell.cpp.o

Cell.i: Cell.cpp.i

.PHONY : Cell.i

# target to preprocess a source file
Cell.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Cell.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Cell.cpp.i
.PHONY : Cell.cpp.i

Cell.s: Cell.cpp.s

.PHONY : Cell.s

# target to generate assembly for a file
Cell.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Cell.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Cell.cpp.s
.PHONY : Cell.cpp.s

Command.o: Command.cpp.o

.PHONY : Command.o

# target to build an object file
Command.cpp.o:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Command.cpp.o
.PHONY : Command.cpp.o

Command.i: Command.cpp.i

.PHONY : Command.i

# target to preprocess a source file
Command.cpp.i:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Command.cpp.i
.PHONY : Command.cpp.i

Command.s: Command.cpp.s

.PHONY : Command.s

# target to generate assembly for a file
Command.cpp.s:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Command.cpp.s
.PHONY : Command.cpp.s

Expression.o: Expression.cpp.o

.PHONY : Expression.o

# target to build an object file
Expression.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Expression.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Expression.cpp.o
.PHONY : Expression.cpp.o

Expression.i: Expression.cpp.i

.PHONY : Expression.i

# target to preprocess a source file
Expression.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Expression.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Expression.cpp.i
.PHONY : Expression.cpp.i

Expression.s: Expression.cpp.s

.PHONY : Expression.s

# target to generate assembly for a file
Expression.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Expression.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Expression.cpp.s
.PHONY : Expression.cpp.s

Model.o: Model.cpp.o

.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i

.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s

.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Model.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Model.cpp.s
.PHONY : Model.cpp.s

Number.o: Number.cpp.o

.PHONY : Number.o

# target to build an object file
Number.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Number.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Number.cpp.o
.PHONY : Number.cpp.o

Number.i: Number.cpp.i

.PHONY : Number.i

# target to preprocess a source file
Number.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Number.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Number.cpp.i
.PHONY : Number.cpp.i

Number.s: Number.cpp.s

.PHONY : Number.s

# target to generate assembly for a file
Number.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Number.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Number.cpp.s
.PHONY : Number.cpp.s

Operator.o: Operator.cpp.o

.PHONY : Operator.o

# target to build an object file
Operator.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Operator.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Operator.cpp.o
.PHONY : Operator.cpp.o

Operator.i: Operator.cpp.i

.PHONY : Operator.i

# target to preprocess a source file
Operator.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Operator.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Operator.cpp.i
.PHONY : Operator.cpp.i

Operator.s: Operator.cpp.s

.PHONY : Operator.s

# target to generate assembly for a file
Operator.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Operator.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Operator.cpp.s
.PHONY : Operator.cpp.s

Reference.o: Reference.cpp.o

.PHONY : Reference.o

# target to build an object file
Reference.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Reference.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Reference.cpp.o
.PHONY : Reference.cpp.o

Reference.i: Reference.cpp.i

.PHONY : Reference.i

# target to preprocess a source file
Reference.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Reference.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Reference.cpp.i
.PHONY : Reference.cpp.i

Reference.s: Reference.cpp.s

.PHONY : Reference.s

# target to generate assembly for a file
Reference.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Reference.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Reference.cpp.s
.PHONY : Reference.cpp.s

Text.o: Text.cpp.o

.PHONY : Text.o

# target to build an object file
Text.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Text.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Text.cpp.o
.PHONY : Text.cpp.o

Text.i: Text.cpp.i

.PHONY : Text.i

# target to preprocess a source file
Text.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Text.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Text.cpp.i
.PHONY : Text.cpp.i

Text.s: Text.cpp.s

.PHONY : Text.s

# target to generate assembly for a file
Text.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/Text.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/Text.cpp.s
.PHONY : Text.cpp.s

View.o: View.cpp.o

.PHONY : View.o

# target to build an object file
View.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View.cpp.o
.PHONY : View.cpp.o

View.i: View.cpp.i

.PHONY : View.i

# target to preprocess a source file
View.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View.cpp.i
.PHONY : View.cpp.i

View.s: View.cpp.s

.PHONY : View.s

# target to generate assembly for a file
View.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/View.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/View.cpp.s
.PHONY : View.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ncurses"
	@echo "... editor"
	@echo "... Bool.o"
	@echo "... Bool.i"
	@echo "... Bool.s"
	@echo "... Cell.o"
	@echo "... Cell.i"
	@echo "... Cell.s"
	@echo "... Command.o"
	@echo "... Command.i"
	@echo "... Command.s"
	@echo "... Expression.o"
	@echo "... Expression.i"
	@echo "... Expression.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... Number.o"
	@echo "... Number.i"
	@echo "... Number.s"
	@echo "... Operator.o"
	@echo "... Operator.i"
	@echo "... Operator.s"
	@echo "... Reference.o"
	@echo "... Reference.i"
	@echo "... Reference.s"
	@echo "... Text.o"
	@echo "... Text.i"
	@echo "... Text.s"
	@echo "... View.o"
	@echo "... View.i"
	@echo "... View.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

